
import numpy as np
from .. import bolt


def instance2vec(dataset, ivoc, word2vec):
    """Convert the frequency vector of document to vector
    generated by word2vec
    """
    dim = word2vec.layer1_size
    instances = []
    for x in dataset.instances:
        vec = np.zeros(dim)
        for wi, freq in x["f0"]:
            vec += word2vec[ivoc[w]] * freq
        instances.append(x)

    instances = bolt.io.fromlist(instances, np.object)
    classes = np.unique(dataset.labels)
    return bolt.MemoryDataset(dim, instances, dataset.labels), classes